---
abstract: 'plugin to Email::Store to parse and save message headers'
author:
  - 'Chisel Wright <cpan@herlpacker.co.uk>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Store-Header
no_index:
  directory:
    - inc
    - t
requires:
  Email::Store: 0
  Mail::Header: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.4
